version: '3'

services:
  db:
    image: mysql/mysql-server
    container_name: db-mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    networks:
      - net_db
    environment:
      MYSQL_ROOT_PASSWORD: pwd123456 
    volumes: 
      - /mysql/mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  web:
    build: .
    container_name: 'aspnetcore'
    ports:
      - '8003:80' 
    depends_on:
      - db
volumes:
  mysql-data:
    external: true
networks:
  net_db:
    external: true

